### ISSUE TITLE
Missing ng g service

### ISSUE THREAD

**Issue by DaGLiMiOuX** [4ern/angular-cli-for-sublime-text#5]
Hi.

The plugin is amazing, but is missing the `ng g service <path/to/service-name>` which I needed for my Angular instance.

I would like to get notified when it is ready or let me know if I can help with a PR or something like that.

Thanks! :)

**Comment by kld87** [comment]
@4ern it looks like this was added in a pull ~4 months ago, but an updated release hasn't been published? Package control is still installing the 3y/o version... would be convenient to add a new release w/ this included?

**Comment by 4ern** [comment]
hi I do not work with sublime and currently have no time to add a new release. If you want, you can take it over. Just tell me what exactly you need.

**Comment by kld87** [comment]
@4ern Thanks for responding. I'd be happy to do this since it looks like it wouldn't be a ton of effort to get updated and then maintain going forward; I've got a decent level of competency w/ Python and the repo looks pretty straight-forward.

Looks like the two options are for you to transfer ownership of the repo:

- https://help.github.com/en/articles/transferring-a-repository

...or add me as a collaborator:

- https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository
- https://help.github.com/en/articles/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account

Both look to provide enough control for me to get this updated thru into Sublime.. w/ a transfer it looks like the old URL will still work so nothing should break there (I'd probably submit pulls to Package Control to get it changed though).

I guess it's up to you re: if you want to maintain control/ownership (add collaborator), or just be rid of it (transfer). Latter would probably involve you getting fewer notifications about it.
